doit

diff --git a/.github/workflows/sphinx-build-and-deploy.yaml b/.github/workflows/sphinx-build-and-deploy.yaml
--- a/.github/workflows/sphinx-build-and-deploy.yaml
+++ b/.github/workflows/sphinx-build-and-deploy.yaml
@@ -61,33 +61,72 @@ jobs:
     needs: setup
     steps:
 
-      - name: List docs directory in setup
-        run: |
-          ls
-      - name: Download docs folder
-        uses: actions/download-artifact@v4
+      - uses: actions/checkout@v1 
+      - uses: ammaraskar/sphinx-action@master
         with:
-          name: docs-folder
-          path: docs
+            docs-folder: "docs/" 
+    
+      - uses: ammaraskar/sphinx-action@master
+        with:
+            build-command: "sphinx-build -b html . _build"
+            docs-folder: "docs/"
 
-      # Step 4. Install dependencies and generate documentation
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-      - name: Install dependencies
-        run: |
-          pip install sphinx sphinx_rtd_theme myst_parser
-      - name: Sphinx build
-        run: |
-          sphinx-build docs _build
-        
-      - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
+      # Save HTML page artifact
+      - name: "Upload Sphinx Artifact"
+        # Specify id for referencing output artifact
+        id: upload_artifact
+        uses: actions/upload-artifact@v4
         with:
-          publish_branch: gh-pages
+          path: docs/_build/html/
+      
+   # Publish built docs to gh-pages branch.
+    # ===============================
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/VegraD/sphinx_test.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: _build/
-          #force_orphan: true
+
+#      - name: List docs directory in setup
+#        run: |
+#          ls
+#      - name: Download docs folder
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: docs-folder
+#          path: docs
+#
+#      # Step 4. Install dependencies and generate documentation
+#      - uses: actions/checkout@v4
+#      - uses: actions/setup-python@v5
+#      - name: Install dependencies
+#        run: |
+#          pip install sphinx sphinx_rtd_theme myst_parser
+#      - name: Sphinx build
+#        run: |
+#          sphinx-build docs _build
+#        
+#      - name: Deploy to GitHub Pages
+#        uses: peaceiris/actions-gh-pages@v3
+#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
+#        with:
+#          publish_branch: gh-pages
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#          publish_dir: _build/
+#          #force_orphan: true
 
   #build-deploy:
   #  runs-on: ubuntu-latest
