test automake folders

diff --git a/.github/workflows/sphinx-build-and-deploy.yaml b/.github/workflows/sphinx-build-and-deploy.yaml
--- a/.github/workflows/sphinx-build-and-deploy.yaml
+++ b/.github/workflows/sphinx-build-and-deploy.yaml
@@ -1,50 +1,70 @@
-name: "PR Sphinx Docs Check and Deploy"
-on:
+name: "Quickstart and fill Sphinx"
+on: 
   push:
     branches:
       - main
 
 jobs:
-  # Build the sphinx docs
-  build:
+  check:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v1 
-      - uses: ammaraskar/sphinx-action@master
-        with:
-            docs-folder: "docs/" 
-    
-      - uses: ammaraskar/sphinx-action@master
-        with:
-            build-command: "sphinx-build -b html . _build"
-            docs-folder: "docs/"
+    - name: Sphinx exist and make
+      if: ${{ hashFiles('docs/conf.py') == '' }}
+      run: |
+        sphinx-quickstart
 
-      # Save HTML page artifact
-      - name: "Upload Sphinx Artifact"
-        # Specify id for referencing output artifact
-        id: upload_artifact
-        uses: actions/upload-artifact@v4
-        with:
-          path: docs/_build/html/
-      
-   # Publish built docs to gh-pages branch.
-    # ===============================
-      - name: Commit documentation changes
-        run: |
-          git clone https://github.com/VegraD/sphinx_test.git --branch gh-pages --single-branch gh-pages
-          cp -r docs/_build/html/* gh-pages/
-          cd gh-pages
-          touch .nojekyll
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add .
-          git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          branch: gh-pages
-          directory: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-    # ===============================
+
+
+
+
+
+#name: "PR Sphinx Docs Check and Deploy"
+#on:
+#  push:
+#    branches:
+#      - main
+#
+#jobs:
+#  # Build the sphinx docs
+#  build:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v1 
+#      - uses: ammaraskar/sphinx-action@master
+#        with:
+#            docs-folder: "docs/" 
+#    
+#      - uses: ammaraskar/sphinx-action@master
+#        with:
+#            build-command: "sphinx-build -b html . _build"
+#            docs-folder: "docs/"
+#
+#      # Save HTML page artifact
+#      - name: "Upload Sphinx Artifact"
+#        # Specify id for referencing output artifact
+#        id: upload_artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          path: docs/_build/html/
+#      
+#   # Publish built docs to gh-pages branch.
+#    # ===============================
+#      - name: Commit documentation changes
+#        run: |
+#          git clone https://github.com/VegraD/sphinx_test.git --branch gh-pages --single-branch gh-pages
+#          cp -r docs/_build/html/* gh-pages/
+#          cd gh-pages
+#          touch .nojekyll
+#          git config --local user.email "action@github.com"
+#          git config --local user.name "GitHub Action"
+#          git add .
+#          git commit -m "Update documentation" -a || true
+#        # The above command will fail if no changes were present, so we ignore
+#        # that.
+#      - name: Push changes
+#        uses: ad-m/github-push-action@master
+#        with:
+#          branch: gh-pages
+#          directory: gh-pages
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#    # ===============================
